# Module 01: NumPy for Machine Learning
## Notebook 01: Array Basics and Creation Routines

Welcome to the first notebook in the Machine Learning curriculum! NumPy (**Numerical Python**) is the foundational library for scientific computing and machine learning in Python. High-level ML libraries like **Scikit-Learn, PyTorch, and TensorFlow** are built on top of or closely integrated with NumPy arrays.

---

### Learning Objectives
By the end of this notebook, you will be able to:
1. Explain the differences between Python standard lists and NumPy `ndarray`s.
2. Initialize 1D, 2D, and multi-dimensional arrays using various creation functions.
3. Inspect and understand crucial array metadata attributes (`shape`, `ndim`, `dtype`, `size`, `nbytes`).
4. Select appropriate data types (`float32` vs `float64`) for machine learning workloads.
5. Cast array types safely and optimize memory consumption.

### 1. Why NumPy for Machine Learning?

In Machine Learning, datasets are represented as matrices and tensors:
- **Tabular Data**: 2D array of shape $(N, D)$ where $N$ is the number of samples and $D$ is the number of features.
- **Images**: 3D or 4D arrays of shape $(H, W, C)$ or $(B, H, W, C)$ (Batch, Height, Width, Channels).
- **Time Series / NLP**: 3D arrays of shape $(B, T, D)$ (Batch, Timesteps, Embedding Dimensions).

Standard Python lists store pointers to Python objects scattered across memory. In contrast, NumPy arrays store elements in a **contiguous block of memory** with a uniform data type. This allows:
1. **Cache locality**: The CPU cache pre-fetches contiguous memory, making data access orders of magnitude faster.
2. **SIMD vectorization**: Modern CPUs can apply Single Instruction Multiple Data operations simultaneously on contiguous chunks.
3. **No interpreter overhead**: Computation happens in compiled C/Fortran code without type-checking each element.

In [1]:
import numpy as np
import sys
import time

print(f"NumPy version: {np.__version__}")

NumPy version: 2.5.3


#### Performance Comparison: Python List vs. NumPy Array

Let's verify the performance advantage by squaring 1,000,000 numbers using both approaches.

In [2]:
# Squaring 1,000,000 numbers using standard Python list
size = 1_000_000
python_list = list(range(size))

start_time = time.time()
squared_list = [x ** 2 for x in python_list]
list_duration = time.time() - start_time

# Squaring using NumPy array
numpy_array = np.arange(size)

start_time = time.time()
squared_array = numpy_array ** 2
numpy_duration = time.time() - start_time

print(f"Python list comprehension time: {list_duration:.4f} seconds")
print(f"NumPy vectorized operation time: {numpy_duration:.4f} seconds")
print(f"NumPy speedup factor: {list_duration / numpy_duration:.1f}x faster!")

Python list comprehension time: 0.1838 seconds
NumPy vectorized operation time: 0.0057 seconds
NumPy speedup factor: 32.1x faster!


---
### 2. Creating Arrays from Existing Data

The simplest way to create an `ndarray` is using `np.array()` with Python lists or nested lists.

In [3]:
# 1D Array (Vector) - e.g., target labels y in regression
vector_1d = np.array([1.5, 2.7, 3.9, 4.1, 5.0])
print("1D Array:")
print(vector_1d)
print(f"Shape: {vector_1d.shape}, Dimensions: {vector_1d.ndim}")

# 2D Array (Matrix) - e.g., feature matrix X with 3 samples and 4 features
matrix_2d = np.array([
    [10, 20, 30, 40],
    [15, 25, 35, 45],
    [12, 22, 32, 42]
])
print("\n2D Feature Matrix X:")
print(matrix_2d)
print(f"Shape: {matrix_2d.shape}, Dimensions: {matrix_2d.ndim}")

1D Array:
[1.5 2.7 3.9 4.1 5. ]
Shape: (5,), Dimensions: 1

2D Feature Matrix X:
[[10 20 30 40]
 [15 25 35 45]
 [12 22 32 42]]
Shape: (3, 4), Dimensions: 2


---
### 3. Built-in Array Creation Routines

NumPy provides specialized functions to generate arrays of specific shapes and patterns without manually defining lists.

#### A. Constant Value Arrays (`zeros`, `ones`, `full`, `empty`)
- `np.zeros(shape)`: Useful for zero-initializing model weights or bias vectors.
- `np.ones(shape)`: Useful for bias terms in linear regression ($x_0 = 1$).
- `np.full(shape, value)`: Fill an array with any arbitrary scalar.
- `np.empty(shape)`: Allocates uninitialized memory without clearing it (very fast, but contains arbitrary garbage values!).

In [4]:
# Zeros array of shape (3, 3)
zero_weights = np.zeros(shape=(3, 3), dtype=np.float32)
print("Zeros (3x3):\n", zero_weights)

# Ones array of shape (2, 4)
bias_vector = np.ones(shape=(2, 4), dtype=np.float32)
print("\nOnes (2x4):\n", bias_vector)

# Full array with a specific constant (e.g., initial baseline prediction = 42.0)
filled_array = np.full(shape=(2, 3), fill_value=42.0)
print("\nFull with 42.0 (2x3):\n", filled_array)

# Empty array (uninitialized memory allocation)
uninitialized = np.empty(shape=(2, 2))
print("\nEmpty (uninitialized memory):\n", uninitialized)

Zeros (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones (2x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Full with 42.0 (2x3):
 [[42. 42. 42.]
 [42. 42. 42.]]

Empty (uninitialized memory):
 [[0.0078125 0.0078125]
 [0.0078125 0.0078125]]


#### B. Numerical Sequences: `arange` vs `linspace`

- `np.arange(start, stop, step)`: Half-open interval `[start, stop)` with a given step.
- `np.linspace(start, stop, num)`: Closed interval `[start, stop]` with an exact count of evenly spaced samples.

> **Important Caveat for Machine Learning:**
> When using floating-point step sizes with `arange`, floating point rounding errors can cause the final number of elements to be unpredictable.
> **Best Practice**: Always prefer `np.linspace` when you need floating-point sequences (e.g., plotting loss curves or creating parameter grids)!

In [5]:
# np.arange with integer step
int_seq = np.arange(0, 20, 2)
print("arange [0, 20, step=2]:", int_seq)

# np.linspace for continuous parameter exploration
# E.g., learning rate candidate values between 0.001 and 0.1
learning_rates = np.linspace(0.001, 0.1, num=10)
print("\nlinspace 10 values in [0.001, 0.1]:\n", learning_rates)

# Decision boundary evaluation grid
grid_points = np.linspace(-5.0, 5.0, num=5)
print("\nGrid points [-5, 5]:", grid_points)

arange [0, 20, step=2]: [ 0  2  4  6  8 10 12 14 16 18]

linspace 10 values in [0.001, 0.1]:
 [0.001 0.012 0.023 0.034 0.045 0.056 0.067 0.078 0.089 0.1  ]

Grid points [-5, 5]: [-5.  -2.5  0.   2.5  5. ]


#### C. Identity and Diagonal Matrices

- `np.eye(N)` or `np.identity(N)`: Identity matrix $I_N$, essential for $L_2$ regularization (Ridge regression penalty: $(X^T X + \lambda I)^{-1}$).
- `np.diag(v)`: Extracts a diagonal from a matrix or constructs a diagonal matrix from a 1D vector.

In [6]:
# Identity matrix of size 4x4
identity_matrix = np.eye(4)
print("Identity Matrix (4x4):\n", identity_matrix)

# Constructing a diagonal covariance / weight matrix
diagonal_weights = np.diag([1.5, 3.0, 0.5])
print("\nDiagonal Matrix from vector [1.5, 3.0, 0.5]:\n", diagonal_weights)

# Extracting the diagonal
extracted = np.diag(diagonal_weights)
print("\nExtracted diagonal:", extracted)

Identity Matrix (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Diagonal Matrix from vector [1.5, 3.0, 0.5]:
 [[1.5 0.  0. ]
 [0.  3.  0. ]
 [0.  0.  0.5]]

Extracted diagonal: [1.5 3.  0.5]


---
### 4. Essential Array Metadata & Memory Attributes

Understanding array properties helps diagnose shape mismatch errors (the most common bug in ML model training!).

Key attributes:
| Attribute | Description | ML Context |
|---|---|---|
| `arr.ndim` | Number of dimensions | 1 = vector, 2 = matrix, 3+ = tensor |
| `arr.shape` | Tuple of dimensions | $(N_{samples}, N_{features})$ |
| `arr.size` | Total number of elements | $\prod 	ext{shape}$ |
| `arr.dtype` | Data type of elements | Precision & memory layout |
| `arr.itemsize` | Bytes per single element | E.g., float64 = 8 bytes, float32 = 4 bytes |
| `arr.nbytes` | Total bytes consumed | `arr.size * arr.itemsize` |

In [7]:
sample_tensor = np.ones((100, 28, 28), dtype=np.float32)

print(f"Number of dimensions (.ndim):    {sample_tensor.ndim}")
print(f"Array shape (.shape):            {sample_tensor.shape}")
print(f"Total elements (.size):          {sample_tensor.size:,}")
print(f"Data type (.dtype):              {sample_tensor.dtype}")
print(f"Bytes per element (.itemsize):   {sample_tensor.itemsize} bytes")
print(f"Total array memory (.nbytes):    {sample_tensor.nbytes:,} bytes ({sample_tensor.nbytes / 1024:.2f} KB)")

Number of dimensions (.ndim):    3
Array shape (.shape):            (100, 28, 28)
Total elements (.size):          78,400
Data type (.dtype):              float32
Bytes per element (.itemsize):   4 bytes
Total array memory (.nbytes):    313,600 bytes (306.25 KB)


---
### 5. Data Types and Type Casting (`.astype()`)

In standard Python, integers have arbitrary precision and floats are 64-bit.
In Machine Learning:
- **`float64` (double precision)**: Default in NumPy. High precision, but doubles memory usage and slows down GPU/CPU matrix multiplication.
- **`float32` (single precision)**: Industry standard for Deep Learning and large-scale ML. Halves memory consumption with negligible impact on convergence.
- **`int32` / `int64`**: Used for categorical indices, class labels, and cluster IDs.
- **`bool_`**: Used for conditional masks and filtering.

In [8]:
# Default float is float64
default_arr = np.array([1.0, 2.5, 3.8])
print("Default dtype:", default_arr.dtype)

# Downcasting to float32 for ML memory efficiency
float32_arr = default_arr.astype(np.float32)
print("Casted dtype: ", float32_arr.dtype)
print(f"Original itemsize: {default_arr.itemsize} bytes | Downcasted itemsize: {float32_arr.itemsize} bytes")

# Converting continuous probabilities into binary prediction labels (0 or 1)
probabilities = np.array([0.15, 0.72, 0.49, 0.91, 0.33])
binary_predictions = (probabilities >= 0.5).astype(np.int32)
print("\nProbabilities:       ", probabilities)
print("Binary Predictions:  ", binary_predictions)

Default dtype: float64
Casted dtype:  float32
Original itemsize: 8 bytes | Downcasted itemsize: 4 bytes

Probabilities:        [0.15 0.72 0.49 0.91 0.33]
Binary Predictions:   [0 1 0 1 0]


### Summary & Next Steps
In this notebook, you mastered:
- The architectural reasons behind NumPy's speed and efficiency.
- Core array creation routines: `np.array`, `zeros`, `ones`, `arange`, `linspace`, `eye`.
- Inspecting dimensions, shapes, and memory attributes.
- Selecting appropriate floating point precision for ML workflows.

**Next Notebook:** `02_indexing_slicing_and_reshaping.ipynb` — Learn multi-dimensional slicing, views vs copies, and tensor reshaping.